stages:
  - "build"
  - "test"
  - "deploy"

# variables:
#   DOCKERHUB_USERNAME: "amirerfant" # Replace with your Docker Hub username
#   DOCKERHUB_IMAGE: "amirerfant/torob-chatbot" 
#   DOCKER_DRIVER: overlay2
#   DOCKER_TLS_CERTDIR: ""
#   DOCKER_HOST: "tcp://docker:2375"
#   IMAGE: "$DOCKERHUB_IMAGE:${CI_COMMIT_SHORT_SHA}"


#   # DOCKER_HOST: "tcp://docker:2376"
#   # DOCKER_TLS_CERTDIR: ""


variables:
  IMAGE: "registry.hamdocker.ir/torob-bootcamp-1402/amirerfan-torob-chatbot:${CI_COMMIT_SHORT_SHA}"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build-job:
    services:
      - docker:dind
    tags:
      - "2"
    stage: build
    image: docker:stable
    script:
        - mkdir -p ~/.docker && cat "$DOCKER_AUTH" > ~/.docker/config.json
        - docker build -t $IMAGE ./torob_chatbot
        - docker push $IMAGE



deploy-job:
    tags:
      - "2"
    image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
    only:
       refs:
            - main
    script:
        - darkube deploy --token ${DEPLOY_TOKEN} --app-id ${APP_ID} --image-tag ${CI_COMMIT_SHORT_SHA} 
    stage: deploy

test-job:
    tags:
      - "2"
    services:
      - ankane/pgvector:latest
    variables:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: trust
    stage: test
    image: $IMAGE
    script:
      - python ./torob_chatbot/manage.py test
