stages:
  - "build"
  - "test"
  - "deploy"

variables:
  IMAGE: "registry.hamdocker.ir/torob-bootcamp-1402/amirerfan-torob-chatbot:${CI_COMMIT_SHORT_SHA}"

build-job:
    services:
      - docker:dind
    tags:
      - bootcamp
      - fi
    stage: build
    image: docker:stable
    script:
        - mkdir -p ~/.docker && cat "$DOCKER_AUTH" > ~/.docker/config.json
        - docker build -t $IMAGE ./torob_chatbot
        - docker push $IMAGE


deploy-job:
    tags:
      - bootcamp
      - ir
    image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
    only:
       refs:
            - main
    script:
        - darkube deploy --token ${DEPLOY_TOKEN} --app-id ${APP_ID} --image-tag ${CI_COMMIT_SHORT_SHA} 
    stage: deploy

test-job:
    tags:
      - bootcamp
      - fi
    stage: test
    image: python:3.11-slim
    script:
    - pip install -r ./torob_chatbot/requirements.txt
    - python ./torob_chatbot/manage.py test

