stages:
  - "build"
  - "test"
  - "deploy"

variables:
  IMAGE: "registry.hamdocker.ir/torob-bootcamp-1402/amirerfan-torob-chatbot:${CI_COMMIT_SHORT_SHA}"

build-job:
    services:
      - docker:dind
    tags:
      - bootcamp
      - fi
    stage: build
    image: docker:stable
    variables:
      DOCKER_AUTH_CONFIG: '{ "auths": { "https://index.docker.io/v1/": { "auth": "$DOCKER_AUTH" } }}'
    script:
        - mkdir -p ~/.docker && cat "$DOCKER_AUTH" > ~/.docker/config.json
        - docker build -t $IMAGE ./torob_chatbot
        - docker push $IMAGE


deploy-job:
    tags:
      - bootcamp
      - ir
    image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
    only:
       refs:
            - main
    script:
        - darkube deploy --token ${DEPLOY_TOKEN} --app-id ${APP_ID} --image-tag ${CI_COMMIT_SHORT_SHA} 
    stage: deploy

test-job:
    tags:
      - bootcamp
      - fi
    # services:
    #   - postgres:latest
    # variables:
    #   POSTGRES_DB: $DB_NAME
    #   POSTGRES_USER: $DB_USER
    #   POSTGRES_PASSWORD: $DB_PASSWORD
    #   POSTGRES_HOST_AUTH_METHOD: trust
    stage: test
    image: $IMAGE
    script:
      - python ./torob_chatbot/manage.py test
