stages:
  - "build"
  - "test"
  - "deploy"

variables:
  DOCKERHUB_USERNAME: "amirerfant" # Replace with your Docker Hub username
  DOCKERHUB_IMAGE: "amirerfant/torob-chatbot" 

# variables:
#   IMAGE: "registry.hamdocker.ir/torob-bootcamp-1402/amirerfan-torob-chatbot:${CI_COMMIT_SHORT_SHA}"

build-job:
    services:
      - docker:dind
    tags:
      - cloud-computing
    stage: build
    image: docker:stable
    script:
        # - mkdir -p ~/.docker && cat "$DOCKER_AUTH" > ~/.docker/config.json
        - echo 56325632aA | docker login -u amirerfant --password-stdin
        - docker build -t $DOCKERHUB_IMAGE:${CI_COMMIT_SHORT_SHA} ./torob_chatbot
        - docker push $DOCKERHUB_IMAGE:${CI_COMMIT_SHORT_SHA}


deploy-job:
    tags:
      - cloud-computing
    image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
    only:
       refs:
            - main
    script:
        - darkube deploy --token ${DEPLOY_TOKEN} --app-id ${APP_ID} --image-tag ${CI_COMMIT_SHORT_SHA} 
    stage: deploy

test-job:
    tags:
      - cloud-computing
    services:
      - ankane/pgvector:latest
    variables:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: trust
    stage: test
    image: $IMAGE
    script:
      - python ./torob_chatbot/manage.py test
