# Generated by Django 3.2.12 on 2023-11-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='custom_prompt',
            field=models.TextField(default='You are a helpful assistant.'),
        ),
    ]
