# Generated by Django 3.2.12 on 2023-11-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_message_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='search_vector',
        ),
    ]
