# Generated by Django 3.2.12 on 2023-11-20 14:41

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_message_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
