# Generated by Django 3.2.12 on 2023-11-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_remove_message_show_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='show_original',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
