# Generated by Django 3.2.12 on 2023-11-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_auto_20231120_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotContent',
        ),
    ]
