# Generated by Django 3.2.12 on 2023-11-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_message_show_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='likes',
        ),
    ]
